"""add user.password_hash

Revision ID: 70d46347652d
Revises: 870a57cad751
Create Date: 2026-06-23 13:06:19.762801

"""
from passlib.context import CryptContext
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '70d46347652d'
down_revision: Union[str, Sequence[str], None] = '870a57cad751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

pwd = CryptContext(schemes=["bcrypt"], deprecated="auto")

def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=200), nullable=True))
    op.create_unique_constraint("uq_users_name", "users", ["name"])
    op.execute(
        sa.text("UPDATE users SET password_hash = 'CHANGE_ME'")
    )
    default_hash = pwd.hash("password123")
    op.execute(sa.text("UPDATE users SET password_hash = :h").bindparams(h=default_hash))
    op.alter_column("users", "password_hash", nullable = False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_name", "users", type_="unique")
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
