"""add user.password_hash

Revision ID: 412e1c3f9772
Revises: addb6457dbb1
Create Date: 2026-06-23 12:59:37.433121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

# revision identifiers, used by Alembic.
revision: str = '412e1c3f9772'
down_revision: Union[str, Sequence[str], None] = 'addb6457dbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = {col["name"] for col in inspector.get_columns("users")}

    if "password_hash" not in columns:
        op.add_column('users', sa.Column('password_hash', sa.String(length=200), nullable=False))

    op.alter_column('users', 'username',
                    existing_type=sa.VARCHAR(length=200),
                    type=sa.String(length=200),
                    existing_nullable=False)
    op.create_unique_constraint(None, 'users', ['username'])

    if "password_hash" not in columns:
        default_password = pwd_context.hash("pass123")
        op.execute(sa.text("UPDATE users Set password_hash = :h").bindparams(h=default_password))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_username", 'users', type_='unique')
    op.alter_column('users', 'username',
                    existing_type=sa.String(length=200),
                    type=sa.VARCHAR(length=200),
                    existing_nullable=False)
    op.drop_column('users', 'password_hash')

    # ### end Alembic commands ###
